### ISSUE TITLE
[Bug] ubuntu  failed to run custom build command for `grpcio-sys v0.4.4`

### ISSUE THREAD

**Issue by BeyondMyself** [libra/libra#136]
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
```

** Stack trace/error message **
```
// Paste the output here
```

## System information

./scripts/cli/start_cli_testnet.sh
Building and running client in debug mode.
   Compiling grpcio-sys v0.4.4
   Compiling ring v0.14.6
error: failed to run custom build command for `grpcio-sys v0.4.4`

Caused by:
  process didn't exit successfully: `/home/gitSource/libra/target/debug/build/grpcio-sys-18712f499919ddc1/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=grpc_wrap.cc
cargo:rerun-if-changed=grpc
cargo:rerun-if-env-changed=GRPCIO_SYS_USE_PKG_CONFIG
cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
running: "cmake" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.4.4/grpc" "-DgRPC_INSTALL=false" "-DgRPC_BUILD_CSHARP_EXT=false" "-DgRPC_BUILD_CODEGEN=false" "-DgRPC_BENCHMARK_PROVIDER=none" "-DCMAKE_INSTALL_PREFIX=/home/gitSource/libra/target/debug/build/grpcio-sys-c998cb3e25589d95/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gitSource/libra/target/debug/build/grpcio-sys-c998cb3e25589d95/out/build

--- stderr
CMake Warning at cmake/protobuf.cmake:48 (message):
  gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:140 (include)

CMake Warning at cmake/gflags.cmake:26 (message):
  gRPC_GFLAGS_PROVIDER is "module" but GFLAGS_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:142 (include)

CMake Error at CMakeLists.txt:738 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

CMake Error at CMakeLists.txt:6171 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

CMake Error at CMakeLists.txt:871 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

CMake Error at CMakeLists.txt:1329 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

CMake Error at CMakeLists.txt:1329 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

CMake Error at CMakeLists.txt:7803 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

CMake Error at CMakeLists.txt:1715 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

CMake Error at CMakeLists.txt:1715 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

CMake Error at CMakeLists.txt:8012 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

CMake Error at CMakeLists.txt:2694 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

CMake Error at CMakeLists.txt:2694 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

CMake Error at CMakeLists.txt:8114 (target_compile_options):
  Error evaluating generator expression:

    $<COMPILE_LANGUAGE:CXX>

  Expression did not evaluate to a known generator expression

thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.40/src/lib.rs:832:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Please complete the following information:**
- 
- 
-

**Comment by qq122716072** [comment]
I also encountered the same error
`
root@c2-test:/usr/local/software/git/libra# ./scripts/cli/start_cli_testnet.sh
Building and running client in debug mode.
    Updating crates.io index
    Updating git repository `https://github.com/pingcap/rust-rocksdb.git`
    Updating git repository `https://github.com/alexcrichton/bzip2-rs.git`
    Updating git repository `https://github.com/busyjay/lz4-rs.git`
    Updating git repository `https://github.com/busyjay/rust-snappy.git`
    Updating git repository `https://github.com/gyscos/zstd-rs.git`
   Compiling iovec v0.1.2
   Compiling rand_os v0.1.3
   Compiling rand v0.4.6
   Compiling net2 v0.2.33
   Compiling getrandom v0.1.3
   Compiling num_cpus v1.10.1
   Compiling wait-timeout v0.2.0
   Compiling rand v0.5.6
   Compiling memchr v0.1.11
   Compiling dirs v1.0.5
   Compiling time v0.1.42
   Compiling errno v0.2.4
   Compiling isatty v0.1.9
   Compiling atty v0.2.11
   Compiling thread-id v3.3.0
   Compiling get_if_addrs v0.5.3
   Compiling backtrace-sys v0.1.28
   Compiling grpcio-sys v0.4.4
error: failed to run custom build command for `grpcio-sys v0.4.4`

Caused by:
  process didn't exit successfully: `/usr/local/software/git/libra/target/debug/build/grpcio-sys-18712f499919ddc1/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=grpc_wrap.cc
cargo:rerun-if-changed=grpc
cargo:rerun-if-env-changed=GRPCIO_SYS_USE_PKG_CONFIG
cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
running: "cmake" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.4.4/grpc" "-DgRPC_INSTALL=false" "-DgRPC_BUILD_CSHARP_EXT=false" "-DgRPC_BUILD_CODEGEN=false" "-DgRPC_BENCHMARK_PROVIDER=none" "-DCMAKE_INSTALL_PREFIX=/usr/local/software/git/libra/target/debug/build/grpcio-sys-c998cb3e25589d95/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
-- Configuring incomplete, errors occurred!
See also "/usr/local/software/git/libra/target/debug/build/grpcio-sys-c998cb3e25589d95/out/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/software/git/libra/target/debug/build/grpcio-sys-c998cb3e25589d95/out/build/CMakeFiles/CMakeError.log".

--- stderr
CMake Warning at cmake/protobuf.cmake:48 (message):
  gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:140 (include)


CMake Error at third_party/boringssl/CMakeLists.txt:38 (message):
  Could not find Go


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.40/src/lib.rs:832:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
`

**Comment by taosue** [comment]
so how to solve it?

**Comment by wqfish** [comment]
@qq122716072 your error message says

```
CMake Error at third_party/boringssl/CMakeLists.txt:38 (message):
Could not find Go
```

Can you try installing go?

**Comment by wqfish** [comment]
Hi @BeyondMyself what is the version of your `cmake`? Can you try installing the latest?

**Comment by silhouette14** [comment]
same problem here:
Ubuntu 18.04.2 LTS
cmake version 3.10.2

**Comment by BoundlessCarrot** [comment]
Same issue here.

MacOS Mojave 10.14.5
cmake version 3.14.5

**Comment by npq7721** [comment]
sudo snap install go --classic
to install go and that fix it

**Comment by npq7721** [comment]
but now i get this

  Compiling admission_control_proto v0.1.0 (/home/stacy/libra/admission_control/admission_control_proto)
error: failed to run custom build command for `admission_control_proto v0.1.0 (/home/stacy/libra/admission_control/admission_control_proto)`

Caused by:
  process didn't exit successfully: `/home/stacy/libra/target/debug/build/admission_control_proto-d741184a6093a7c5/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=../../types/src/proto/validator_set.proto
cargo:rerun-if-changed=../../types/src/proto/transaction_info.proto
cargo:rerun-if-changed=../../types/src/proto/proof.proto
cargo:rerun-if-changed=../../types/src/proto/transaction.proto
cargo:rerun-if-changed=../../types/src/proto/validator_change.proto
cargo:rerun-if-changed=../../types/src/proto/vm_errors.proto
cargo:rerun-if-changed=../../types/src/proto/account_state_blob.proto
cargo:rerun-if-changed=../../types/src/proto/validator_public_keys.proto
cargo:rerun-if-changed=../../types/src/proto/ledger_info.proto
cargo:rerun-if-changed=../../types/src/proto/get_with_proof.proto
cargo:rerun-if-changed=../../types/src/proto/events.proto
cargo:rerun-if-changed=../../types/src/proto/access_path.proto
cargo:rerun-if-changed=../../mempool/src/proto/shared/mempool_status.proto
cargo:rerun-if-changed=src/proto/admission_control.proto

--- stderr
admission_control.proto: No such file or directory

**Comment by wayne-china** [comment]
> but now i get this
> 
> Compiling admission_control_proto v0.1.0 (/home/stacy/libra/admission_control/admission_control_proto)
> error: failed to run custom build command for `admission_control_proto v0.1.0 (/home/stacy/libra/admission_control/admission_control_proto)`
> 
> Caused by:
> process didn't exit successfully: `/home/stacy/libra/target/debug/build/admission_control_proto-d741184a6093a7c5/build-script-build` (exit code: 101)
> --- stdout
> cargo:rerun-if-changed=../../types/src/proto/validator_set.proto
> cargo:rerun-if-changed=../../types/src/proto/transaction_info.proto
> cargo:rerun-if-changed=../../types/src/proto/proof.proto
> cargo:rerun-if-changed=../../types/src/proto/transaction.proto
> cargo:rerun-if-changed=../../types/src/proto/validator_change.proto
> cargo:rerun-if-changed=../../types/src/proto/vm_errors.proto
> cargo:rerun-if-changed=../../types/src/proto/account_state_blob.proto
> cargo:rerun-if-changed=../../types/src/proto/validator_public_keys.proto
> cargo:rerun-if-changed=../../types/src/proto/ledger_info.proto
> cargo:rerun-if-changed=../../types/src/proto/get_with_proof.proto
> cargo:rerun-if-changed=../../types/src/proto/events.proto
> cargo:rerun-if-changed=../../types/src/proto/access_path.proto
> cargo:rerun-if-changed=../../mempool/src/proto/shared/mempool_status.proto
> cargo:rerun-if-changed=src/proto/admission_control.proto
> 
> --- stderr
> admission_control.proto: No such file or directory

I meet same error

**Comment by Mick-Duan** [comment]
i met the same error, fixed by update golang and cmake to latest version.  
you can try ;)

**Comment by kphfb** [comment]
If you see proto errors, please try the following: https://github.com/libra/libra/issues/215#issuecomment-505272760

**Comment by icarter09** [comment]
@BeyondMyself and @qq122716072 are either of you still experiencing this issue?

**Comment by dmego** [comment]
Hi,I solved this problem with the following command
>`sudo yum remove cmake -y; sudo yum install cmake3 -y`
>`sudo ln -s /usr/bin/cmake3 /usr/bin/cmake`
>`cargo build`
You can also read this article.[Deploying the Libra Core Blockchain Currency on Amazon EC2](https://blog.cotten.io/deploying-the-libra-core-blockchain-currency-on-amazon-ec2-f832d4bfadc8)

**Comment by fredericfaure** [comment]
Hi, I solved the problem with the install of go :

`sudo apt-get -y install golang`

**Comment by bmwill** [comment]
grpcio-sys is no longer a dependency so this problem should't still be present if building with master.
